name: Build and Test
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  security_tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Clone the GitHub repository on the machine
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install program dependencies
      run: npm install

    - name: Run npm security tests
      run: npm audit

  build_test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Clone the GitHub repository on the machine
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install program dependencies
      run: npm install

    - name: Run integration tests
      run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: [ "build_test", "security_tests" ]
    steps:
        - uses: actions/checkout@v3
        - uses: JorgeLNJunior/render-deploy@v1.4.4
          with:
            service_id: ${{ secrets.SERVICE_ID }}
            api_key: ${{ secrets.RENDER_TOKEN }}
            wait_deploy: true 